import numpy as np

TARGET_RENDER_FPS = 360
PROCESS_SCALE = 0.5
ROI = None
WINDOW_WIDTH = 760
WINDOW_HEIGHT = 460
PLACE_ON_SECOND_MONITOR = True

CURSOR_MINT_RGB = np.array([67, 255, 193])
CURSOR_MINT_TOLERANCE = 28
WHITE_MIN_VALUE = 225
WHITE_MAX_SATURATION = 55
MIN_CURSOR_MINT_RATIO = 0.08
MIN_CURSOR_WHITE_RATIO = 0.08
MIN_RADIUS_CURSOR = 8
MAX_RADIUS_CURSOR = 70
MIN_CIRCULARITY_CURSOR = 0.65

TARGET_RING_MIN_VALUE = 155
TARGET_RING_MAX_SATURATION = 95
MIN_RADIUS_TARGET_CIRCLE = 22
MAX_RADIUS_TARGET_CIRCLE = 110
MIN_TARGET_CIRCLE_AREA = 120
MIN_CIRCULARITY_TARGET_CIRCLE = 0.50
MIN_TARGET_RING_RATIO = 0.18
MAX_TARGET_CENTER_WHITE_RATIO = 0.38

ENABLE_MOUSE_ASSIST = True

ASSIST_INPUT_MODE = "tablet_pulse"
ASSIST_TABLET_REQUIRE_MOTION = False
ASSIST_TABLET_PULSE_ENABLED = True
ASSIST_TABLET_PULSE_MS = 120
ASSIST_TABLET_PULSE_COOLDOWN_MS = 35
ASSIST_TABLET_INTERRUPT_DOT = 0.25
ASSIST_TABLET_MAX_TARGET_SHIFT = 120
ASSIST_TABLET_PULSE_START_FORCE = 0.22
ASSIST_TABLET_PULSE_ACCEL = 2.80
ASSIST_TABLET_PULSE_MAX_STEP = 220
ASSIST_TABLET_PULSE_REPEAT_COUNT = 4
ASSIST_TABLET_PULSE_SNAP_DISTANCE = 24

ASSIST_FORCE = 0.40
ASSIST_MAX_STEP = 12
ASSIST_MIN_CURSOR_SPEED = 1.0
ASSIST_ACTIVATION_DOT = 0.45
ASSIST_MIN_DISTANCE = 4
ASSIST_DEADZONE_RADIUS_FACTOR = 0.35
ASSIST_UPDATE_HZ = 360
ASSIST_TARGET_MODE = "nearest"
